### ISSUE TITLE
Error in EvoMaster 3.1.0: Black-Box Testing Initialization Failure with InvocationTargetException and NoSuchMethodError

### ISSUE THREAD

**Issue by agrawalhemant5393** [WebFuzzing/EvoMaster#1069]
* EvoMaster version: 3.1.0
* Loading configuration file from: D:\Codes\em.yaml
* WARNING: You are doing Black-Box testing, but you did not specify the 'problemType'. The system will default to RESTful API testing.
* Initializing...
16:38:29.967 [main] WARN  o.t.u.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/C:/Users/hagrawal/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: C:\Users\hagrawal\.testcontainers.properties (The system cannot find the file specified)
16:38:31.856 [main] WARN  o.e.c.problem.rest.param.BodyParam - Not supported data type: multipart/form-data
* There are 20 usable RESTful API endpoints defined in the schema configuration
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@5e519ad3
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.onProvision(LifecycleListenerModule.java:51)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:65)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.onProvision(LifecycleListenerModule.java:51)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:65)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.onProvision(LifecycleListenerModule.java:51)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:65)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:427)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:165)
        at org.evomaster.core.Main$Companion.main(Main.kt:85)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.NoSuchMethodError: 'java.util.List java.util.List.reversed()'
        at org.evomaster.core.problem.util.BindingBuilder.buildBindBodyAndOther(BindingBuilder.kt:304)
        at org.evomaster.core.problem.util.BindingBuilder.buildBindBodyParam(BindingBuilder.kt:217)
        at org.evomaster.core.problem.util.BindingBuilder.buildBindBetweenParams(BindingBuilder.kt:163)
        at org.evomaster.core.problem.util.BindingBuilder.buildBindingPairsInRestAction(BindingBuilder.kt:84)
        at org.evomaster.core.problem.util.BindingBuilder.bindParamsInRestAction(BindingBuilder.kt:68)
        at org.evomaster.core.problem.util.BindingBuilder.bindParamsInRestAction$default(BindingBuilder.kt:67)
        at org.evomaster.core.problem.rest.RestCallAction.postRandomizedChecks(RestCallAction.kt:248)
        at org.evomaster.core.search.action.Action.doInitialize(Action.kt:76)
        at org.evomaster.core.problem.rest.service.RestSampler.createSingleCallOnEachEndpoint(RestSampler.kt:284)
        at org.evomaster.core.problem.rest.service.RestSampler.customizeAdHocInitialIndividuals(RestSampler.kt:271)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initAdHocInitialIndividuals(AbstractRestSampler.kt:218)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initForBlackBox(AbstractRestSampler.kt:317)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:69)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
        ... 75 common frames omitted

**Comment by arcuri82** [comment]
Hi @agrawalhemant5393 ,
 thanks for reporting this bug. I have seen something related when dealing with JDK 21, but thought it was fixed.
Can you please clarify this for me:

1) how are you running EvoMaster? from JAR, or from a MSI/DEB installer? 
2) if from jar, what version of JDK are you using? 

thx

**Comment by agrawalhemant5393** [comment]
I am testing this using jar directly using JDK -17.

**Comment by arcuri82** [comment]
for now, until it is investigated and fixed, i ll suggest to use EM from one of its installers, or try with a different JDK

**Comment by sathiyajith** [comment]
@arcuri82 I'm also facing this exact error. I'm using JDK-11.0.24.

**Comment by arcuri82** [comment]
thx @sathiyajith 
it looks like a critical issue. i have no idea why it was not caught in CI (as we build and test with JDK 17 and 11).
unfortunately I am very busy this and next week.
besides trying to use one of the installers, if that doesn't work either, I would suggest to revert to 3.0.0 until I make a hot fix maybe in 7-10 days from now

**Comment by arcuri82** [comment]
@agrawalhemant5393 @sathiyajith 
thanks for bring this issue to my attention.

I understand what is going on.

The jar file for the release is wrongly built with latest LTS, which is now JDK 21. That was not a problem before, because Kotlin compiler was targeing JDK 8 bytecode.
The problem is with extension function `reversed()`, which is now introduced as well in Java sinch JDK 21. In those cases, Kotlin does not use the extension function, but rather the native function in JDK. Which leads to a crash when using version below 21 :(

If you need to use JAR instead of an installer, then should use JDK 21 to run EM.

**Comment by arcuri82** [comment]
this should be fixed now in the new 3.2.0 release

**Comment by arcuri82** [comment]
Dear @agrawalhemant5393 ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
