### ISSUE TITLE
java.util.NoSuchElementException: Key org.evomaster.core.search.gene.optional.OptionalGene@5dc8227c is missing in the map.

### ISSUE THREAD

**Issue by sx18170** [WebFuzzing/EvoMaster#1150]
java.util.NoSuchElementException: Key org.evomaster.core.search.gene.optional.OptionalGene@5dc8227c is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:349)
        at org.evomaster.core.search.gene.datetime.TimeGene.adaptiveSelectSubsetToMutate(TimeGene.kt:116)
        at org.evomaster.core.search.gene.Gene.selectSubsetToMutate(Gene.kt:663)
        at org.evomaster.core.search.gene.Gene.standardMutation(Gene.kt:572)
        at org.evomaster.core.search.gene.Gene.standardMutation(Gene.kt:579)
        at org.evomaster.core.search.gene.Gene.standardMutation(Gene.kt:579)
        at org.evomaster.core.search.service.mutator.StandardMutator.innerMutate(StandardMutator.kt:277)
        at org.evomaster.core.search.service.mutator.StandardMutator.mutate(StandardMutator.kt:299)
        at org.evomaster.core.search.service.mutator.Mutator.mutateAndSave(Mutator.kt:152)
        at org.evomaster.core.search.algorithms.MioAlgorithm.searchOnce(MioAlgorithm.kt:48)
        at org.evomaster.core.search.service.SearchAlgorithm.search(SearchAlgorithm.kt:73)
        at org.evomaster.core.Main$Companion.run(Main.kt:558)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:174)
        at org.evomaster.core.Main$Companion.main(Main.kt:85)
        at org.evomaster.core.Main.main(Main.kt)
.

Other important info:
- version of EvoMaster (EM) used : v3.3.0
- how EM is run (eg, if from JAR or from one of its OS installers) : windows installer evomaster-3.3.0.msi
- version of applicable runtimes (eg, JVM, NodeJS and .Net). For Java, can paste the output of `java --version`
    $ java --version
    openjdk 17.0.13 2024-10-15
    OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
    OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode, sharing)

- command-line options used to run EM
evomaster --maxTime 1h --prematureStop 600s

**Comment by arcuri82** [comment]
hi @sx18170 
 thx for reporting this bug. Until it is fixed, you can try to run EvoMaster with `--adaptiveGeneSelectionMethod NONE` to see if that part of the code is skipped (ie functionality deactivated)

**Comment by arcuri82** [comment]
@sx18170 issue should now be fixed in latest 3.4.0 release
